package org.springframework.samples.owlmarketplace.model;

// javax.persistence package imports

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

@Entity // Create database entity
@Table(name = "customer") // Use customer table in MySQL
public class Customer implements Serializable {

	@Id // MySQL table ID field
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long cId; // Long ID is autogenerated

	@Column(name = "first_name")
	private String firstName;

	@Column(name = "last_name")
	private String lastName;

	@Column(name = "email")
	private String email;

	@Column(name = "password")
	private String password;

	@Column(name = "password_confirmation")
	private String passwordConfirmation;

	@Column(name = "signup_date")
	private Date signUpDate = new Date();

	@Column(name = "zip")
	private String zip;

	// City and state columns not currently used but added for future implementations
	@Column(name = "city")
	private String city;

	@Column(name = "state")
	private String state;

	// Getters and Setters
	public long getcId() {
		return cId;
	}

	public void setcId(long Id) {
		this.cId = Id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String lastName) {
		this.firstName = lastName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPasswordConfirmation() {
		return passwordConfirmation;
	}

	public void setPasswordConfirmation(String passwordConfirmation) {
		this.passwordConfirmation = passwordConfirmation;
	}

	public Date getSignUpDate() {
		return signUpDate;
	}

	public void setSignUpDate(Date signUpDate) {
		this.signUpDate = signUpDate;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Override
	public String toString() {
		String customerString = "";
		customerString += ("Customer ID: " + this.getcId() + "\n" + "First Name: " + this.getFirstName() + "\n"
				+ "Last Name: " + this.getLastName() + "\n" + "Email: " + this.getEmail() + "\n" +
				// "Password: " + this.getCustomerPassword() + "\n" +
				"Hidden Password: " + this.hidePassword() + "\n" + "Sign Up Date: " + this.getSignUpDate() + "\n"
				+ "City: " + this.getCity() + "\n" + "State: " + this.getState() + "\n" + "Zip: " + this.getZip()
				+ "\n");
		return customerString;
	}

	public String hidePassword() {
		String hiddenPassword = "";
		for (int i = 0; i < getPassword().length(); i++) {
			hiddenPassword += "*";
		}
		return hiddenPassword;
	}
	// Code used for testing/development
	// // Customers can have many loan apps. Loan apps can have many customers (cosigners)
	// @ManyToMany(mappedBy="customers") // Mapped by customers variable in LoanApps
	// @JsonIgnore
	// public Set<LoanApp> loanApps = new HashSet<>();

	// // Customers can have many loans. Loans can have many customers (cosigners)
	// @ManyToMany(mappedBy="customers") // Mapped by customers variable in Loans
	// @JsonIgnore
	// public Set<Loan> loans = new HashSet<>();
}
