package org.springframework.samples.owlmarketplace.model;

import javax.persistence.*;
import java.io.Serializable;

@Entity // Create/find database entity
@Table(name = "loved_listings") // Create/find table in MySQL db
public class Listing implements Serializable {

	@Id // MySQL table ID field
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long lLId; // Long ID is autogenerated

	@Column(name = "customer_id")
	private long customerId;

	@Column(name = "name")
	private String name;

	@Column(name = "purchase_type")
	private String purchaseType;

	@Column(name = "price")
	private Integer price;

	@Column(name = "city")
	private String city;

	@Column(name = "state")
	private String state;

	@Column(name = "zip", length = 5)
	private String zip;

	@Column(name = "num_beds")
	private Double numBedrooms;

	@Column(name = "num_baths")
	private Double numBathrooms;

	public long getlLId() {
		return lLId;
	}

	public void setlLId(long lLId) {
		this.lLId = lLId;
	}

	public long getCustomerId() {
		return customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPurchaseType() {
		return purchaseType;
	}

	public void setPurchaseType(String purchaseType) {
		this.purchaseType = purchaseType;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public Double getNumBedrooms() {
		return numBedrooms;
	}

	public void setNumBedrooms(Double numBedrooms) {
		this.numBedrooms = numBedrooms;
	}

	public Double getNumBathrooms() {
		return numBathrooms;
	}

	public void setNumBathrooms(Double numBathrooms) {
		this.numBathrooms = numBathrooms;
	}
	// Code used during testing/development
	// public long getPersonnelId() { return personnelId;}
	// public void setPersonnelId(long loanPersonnelId) { this.personnelId =
	// loanPersonnelId;}
	//
	// @ManyToMany(cascade = CascadeType.MERGE) // Customers can have many loans. Loans
	// can have many customers (cosigners)
	// @JoinTable(name = "loan_customer",
	// joinColumns = {@JoinColumn(name = "loan_id")}, // Loan ID
	// inverseJoinColumns = {@JoinColumn(name = "customer_id")}) // Customer ID
	// public Set<Customer> customers = new HashSet<>();

	// public String getStartDate() { return startDate;}
	// public void setStartDate(String loanStartDate) { this.startDate = loanStartDate;}
	//
	// public Double getPrincipal() { return principal;}
	// public void setPrincipal(Double loanPrincipal) { this.principal = loanPrincipal;}
	//
	// public Integer getAPR() { return aPR;}
	// public void setAPR(Integer loanAPR) { this.aPR = loanAPR;}
	//
	// public Integer getTerm() { return term;}
	// public void setTerm(Integer loanTerm) { this.term = loanTerm;}
	//
	// public Double getBalance() { return balance;}
	// public void setBalance(Double loanBalance) { this.balance = loanBalance;}
	//
	// public Set<Customer> getCustomers() { return customers;}
	// public void setCustomers(Set<Customer> customers) { this.customers = customers;}
	//
	// public Customer getPrimaryCustomer() {
	// ArrayList<Customer> customerArrayList = new ArrayList<>(getCustomers());
	// return customerArrayList.get(0);
	// }
	//
	// public Double getMonthlyInterestRate() { return monthlyInterestRate;}
	// public void setMonthlyInterestRate(Double loanMonthlyInterestRate) {
	// this.monthlyInterestRate =
	// loanMonthlyInterestRate;}
	//
	// public Double getMonthlyPayment() { return monthlyPayment;}
	// public void setMonthlyPayment(Double loanMonthlyPayment) { this.monthlyPayment =
	// loanMonthlyPayment;}
	//
	// public String getDoubleWithTwoDecimals(Double doubleValue) {
	// return ("").format("%,.2f" , doubleValue);} // Format doubles with commas and
	// decimal point
	//
	// public void calculateLoanValues(){
	// // Amortized loan balance equation
	// https://www.thebalance.com/loan-payment-calculations-315564
	// // Check balance value with Credit Karma calculator
	// https://www.creditkarma.com/calculators/amortization
	// monthlyInterestRate = getAPR() / 100.0 / MONTHS_PER_YEAR;
	// monthlyPayment = principal /((Math.pow(1 + monthlyInterestRate, term) - 1)/
	// (monthlyInterestRate *Math.pow(1 + monthlyInterestRate, term)));
	// // Round monthly payment and multiply it by loan term to calculate loan balance
	// balance = Math.round((Math.round(monthlyPayment *100.0)/100.0) * term *
	// 100.0)/100.0;
	// System.out.println("Loan Term: " + term);
	// System.out.println("Loan Monthly Interest Rate: " + monthlyInterestRate);
	// System.out.println("Loan Monthly Payment: " + monthlyPayment);
	// System.out.println("Loan Balance: " + balance);
	// }

	// @Override
	// public String toString() {
	// String loanString = "";
	// loanString += (
	// "Loan/Application ID: " + this.getlId() + "\n" +
	// "Loan Start Date: " + this.getStartDate() +
	// "Loan Principal: " + this.getPrincipal() + "\n" +
	// "Loan APR: " + this.getAPR() + "\n" +
	// "Loan Term: " + this.getTerm() + "\n" +
	// "Loan Monthly Interest Rate: " + this.getMonthlyInterestRate() + "\n" +
	// "Loan Monthly Payment: " + this.getMonthlyPayment() + "\n" +
	// "Loan Balance: " + this.getBalance() + "\n" +
	// "Customer Set: " + this.getCustomers());
	// return loanString;
	// }
	// // Removed Date attribute and utilized String for better integration with input
	// type="date" in HTML
	// @Column(name = "start_date")
	// private String startDate; // Date loan funds will be disbursed to customer account
	// @Column(name = "principal")
	// private Double principal;
	// Column(name = "apr")
	// private Integer aPR;
	// @Column(name = "term")
	// private Integer term; // Integer can be null, int cannot
	// @Column(name = "monthly_interest_rate")
	// private double monthlyInterestRate;
	// @Column(name = "monthly_payment")
	// private double monthlyPayment;
	// @Column(name = "balance")
	// private Double balance;
	// @Column(name = "personnel_id")
	// private long personnelId;

	// javax.persistence package imports
	// import com.fasterxml.jackson.annotation.JsonIgnore;
	// import java.text.DecimalFormat;
	// import java.util.Date;

}
