package org.springframework.samples.owlmarketplace.model;

// javax.persistence package imports

import javax.persistence.*;
import java.io.Serializable;

@Entity // Create database entity
@Table(name = "search_object") // Use table in MySQL db
public class SearchObject implements Serializable {

	@Id // MySQL table ID field
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long searchObjectId; // Long ID is autogenerated

	@Column(name = "price")
	private Integer price;

	@Column(name = "purchase_type")
	private String purchaseType;

	@Column(name = "city")
	private String city;

	@Column(name = "state")
	private String state;

	@Column(name = "zip", length = 5)
	private String zip;

	@Column(name = "num_beds")
	private Double numBedrooms;

	@Column(name = "num_baths")
	private Double numBathrooms;

	@Column(name = "keywords")
	private String keywords;

	@Column(name = "customer_id")
	private Long customerId;

	@Column(name = "date")
	private String date;

	public long getCustomerId() {
		return customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public Integer getPrice() {
		return price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	public String getPurchaseType() {
		return purchaseType;
	}

	public void setPurchaseType(String purchaseType) {
		this.purchaseType = purchaseType;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZip() {
		return zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public Double getNumBedrooms() {
		return numBedrooms;
	}

	public void setNumBedrooms(Double numBedrooms) {
		this.numBedrooms = numBedrooms;
	}

	public Double getNumBathrooms() {
		return numBathrooms;
	}

	public void setNumBathrooms(Double numBathrooms) {
		this.numBathrooms = numBathrooms;
	}

	public String getKeywords() {
		return keywords;
	}

	public void setKeywords(String keywords) {
		this.keywords = keywords;
	}

	public long getSearchObjectId() {
		return searchObjectId;
	}

	public void setSearchObjectId(long searchObjectId) {
		this.searchObjectId = searchObjectId;
	}

	public String getDate() {
		return date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	// @Column(name = "date")
	// private String date;
	//
	// @Column(name = "principal")
	// private Double principal;
	//
	// @Column(name = "APR")
	// private Integer aPR;
	//
	// @Column(name = "term")
	// private Integer term; // Integer can be null, int cannot
	//
	// @Column(name = "request_date")
	// private String requestedStartDate; // Date customer would like loan to be disbursed
	// to
	// // bank account
	//
	// @Column(name = "status")
	// private String status = "Pending Review"; // Initialize all loan apps as pending
	//
	// @Column(name = "last_updated")
	// private String dateOfLastUpdate = "Not yet processed"; // Initialize date string as
	// // not processed
	//
	// // Initialize as 0 for unprocessed loan apps, and then set to personnel id once
	// // personnel processes loan app
	// @Column(name = "personnel_id")
	// private long personnelId = 0;
	//
	// public long getPersonnelId() {
	// return personnelId;
	// }
	//
	// public void setPersonnelId(long loanAppPersonnelId) {
	// this.personnelId = loanAppPersonnelId;
	// }
	//
	// @Column(name = "approved_personnel_id")
	// private long approvedPersonnelId = 0;
	//
	// public long getApprovedPersonnelId() {
	// return approvedPersonnelId;
	// }
	//
	// public void setApprovedPersonnelId(long loanProcessedPersonnelId) {
	// this.approvedPersonnelId = loanProcessedPersonnelId;
	// }
	//
	// // Customers can have many loan apps.// Loans apps can have many customers
	// (cosigners)
	// @ManyToMany(cascade = CascadeType.MERGE)
	// @JoinTable(name = "loanapp_customer", joinColumns = { @JoinColumn(name =
	// "loan_app_id") }, // Loan
	// // app
	// // ID
	// inverseJoinColumns = { @JoinColumn(name = "customer_id") }) // customer ID
	// public Set<Customer> customers = new HashSet<>();
	//
	// public long getlAId() {
	// return lAId;
	// }
	//
	// public void setlAId(long loanAppId) {
	// this.lAId = loanAppId;
	// }
	//
	// public String getDate() {
	// return date;
	// }
	//
	// public void setDate(String loanAppDate) {
	// this.date = loanAppDate;
	// }
	//
	// public Double getPrincipal() {
	// return principal;
	// }
	//
	// public void setPrincipal(Double loanPrincipal) {
	// this.principal = loanPrincipal;
	// }
	//
	// public Integer getAPR() {
	// return aPR;
	// }
	//
	// public void setAPR(Integer loanAPR) {
	// this.aPR = loanAPR;
	// }
	//
	// public Integer getTerm() {
	// return term;
	// }
	//
	// public void setTerm(Integer loanTerm) {
	// this.term = loanTerm;
	// }
	//
	// public String getRequestedStartDate() {
	// return requestedStartDate;
	// }
	//
	// public void setRequestedStartDate(String loanAppRequestedStartDate) {
	// this.requestedStartDate = loanAppRequestedStartDate;
	// }
	//
	// public String getStatus() {
	// return status;
	// }
	//
	// public void setStatus(String loanAppStatus) {
	// this.status = loanAppStatus;
	// }
	//
	// public Set<Customer> getCustomers() {
	// return customers;
	// }
	//
	// public void setCustomers(Set<Customer> customers) {
	// this.customers = customers;
	// }
	//
	// public String getDateOfLastUpdate() {
	// return dateOfLastUpdate;
	// }
	//
	// public void setDateOfLastUpdate(String loanAppDateProcessed) {
	// this.dateOfLastUpdate = loanAppDateProcessed;
	// }
	//
	// public Customer getPrimaryCustomer() {
	// ArrayList<Customer> customerArrayList = new ArrayList<>(getCustomers());
	// return customerArrayList.get(0);
	// }
	//
	// public String customerIds() {
	// String customerIds = "";
	// for (Customer c : getCustomers()) {
	// customerIds += c.getcId() + " ";
	// }
	// return customerIds;
	// }
	//
	// public String getDoubleWithTwoDecimals(Double doubleValue) {
	// return ("").format("%,.2f", doubleValue);
	// } // Format doubles with commas and decimal point
	//
	// @Override
	// public String toString() {
	// String loanAppString = "Loan App ID: " + this.getlAId() + "\n" + "Loan App
	// Principal: " + this.getPrincipal()
	// + "\n" + "Loan App Date: " + this.getDate() + "\n" + "Loan App APR: " +
	// this.getAPR() + "\n"
	// + "Loan App Term: " + this.getTerm() + "\n" + "Loan App Requested Start Date: "
	// + this.getRequestedStartDate() + "\n" + "Loan App Status: " + this.getStatus() +
	// "\n"
	// + "Loan App Get Customers: " + this.getCustomers() + "\n" + "Loan App Get Primary
	// Customer: "
	// + this.getPrimaryCustomer() + "\n" + "Loan App Personnel ID: " +
	// this.getPersonnelId() + "\n"
	// + "Loan Processed Personnel ID: " + this.getApprovedPersonnelId() + "\n"
	// + "Loan App Date of Last Update: " + this.getDateOfLastUpdate();
	// return loanAppString;
	// }

}
